from tkinter import *
root=Tk()
root.title("Note pad")
root.geometry("500x500")
root.config(bg="white")

menu=Menu(root)
item=Menu(menu)
item1=Menu(menu)
item2=Menu(menu)
item3=Menu(menu)
item4=Menu(menu)

menu.add_cascade(label="File",menu=item)
item.add_command(label="New")
item.add_command(label="New window")
item.add_command(label="Open")
item.add_command(label="Save ")
item.add_command(label="Save as")
item.add_command(label="Page set up")
item.add_command(label="Print")
item.add_separator()
item.add_command(label="Exit")
root.config(menu=menu)
#-----------------------------------------------------------------------------------------------------------------------------------------


menu.add_cascade(label="Edit",menu=item1)
item1.add_command(label="Undo        Ctrl+Z")
item1.add_command(label="Cut           Ctrl+Z")
item1.add_separator()
item1.add_command(label="Copy        Ctrl+C")
item1.add_command(label="Paste       Ctrl+V")
item1.add_command(label="Delete         Del")
item1.add_separator()
item1.add_command(label="Find...        Ctrl+F")
item1.add_command(label="Find Next   F3")
item1.add_command(label="Replace      Ctrl+H")
item1.add_command(label="Go To...      Ctrl+G")
item1.add_separator()
item1.add_command(label="Select All    Ctrl+A")
item1.add_command(label="Time/Date  F5")
root.config(menu=menu)

menu.add_cascade(label="Format",menu=item2)
item2.add_command(label="Word wrap")
item2.add_command(label="Font...")
root.config(menu=menu)

menu.add_cascade(label="View",menu=item3)
item3.add_command(label="Zoom")
item3.add_command(label="Status Bar")
root.config(menu=menu)
#view help and About NOtepad
menu.add_cascade(label="Help",menu=item4)
item4.add_command(label="View Help")
item4.add_separator()
item4.add_command(label="About Notepad")
root.config(menu=menu)
root.mainloop()
